kind: BuildConfig
apiVersion: v1
metadata:
  labels:
    app: job-example
  name: job-example
spec:
  output: 
    to:
      kind: ImageStreamTag
      name: 'job-example:latest'
  runPolicy: Serial 
  source: 
    git:
      ref: master
      uri: 'https://github.com/patricia1387/job'
  strategy: 
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'python:3.6'
        namespace: openshift
  
