apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: job-example
  name: job-example
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: job-example
    spec:
      containers:
      - name: job-example
        image: python
        command: ["python3.6",  "app.py"]
      restartPolicy: Never
   
